version: '3'

tasks:
  gen-mcp-grpc:
    dir: "mcp"
    cmds:
      - mkdir -p src/gen
      - |
        .venv/bin/python -m grpc_tools.protoc \
        -I src/gen=proto -I proto \
        --python_out=. --pyi_out=. --grpc_python_out=. \
        proto/queue_service.proto

  gen-gateway-grpc:
    dir: "gateway"
    cmds:
      - mkdir -p ./gen/go
      - |
        protoc -I . -I ./proto \
        --go_out ./gen/go/ \
        --go_opt paths=source_relative \
        --go-grpc_out ./gen/go/ \
        --go-grpc_opt paths=source_relative \
        --grpc-gateway_out ./gen/go \
        --grpc-gateway_opt paths=source_relative \
        --openapiv2_out ./gen \
        proto/queue_service.proto